# Generated by Django 5.0.3 on 2024-03-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharityAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('fundacja', 'Fundacja'), ('organizacja', 'Organizacja pozarządowa'), ('zbiórka_lokalna', 'Zbiórka lokalna')], default='fundacja', max_length=20)),
                ('categories', models.ManyToManyField(related_name='institutions', to='CharityAPP.category')),
            ],
        ),
    ]
